import "./globals.css";
import Navbar from "../components/Navbar";
import { Poppins } from "next/font/google";
import Footer from "@/components/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});


export const metadata = {
  
  title: "VELORIA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      <body
        className='overflow-x-hidden'
      >
        <Navbar/>
        <div className="page-wrapper">

        {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
